### ISSUE TITLE
Css selector

### ISSUE THREAD

**Issue by Kuranes** [patmood/git-time-machine#1]
Perhaps make them stay in a config file so that we can update them ?

'.file-box .actions .button-group'
is 
'.file-actions .btn-grp'

(not sure if it's a github update or because I use Stylish extension, so)

Some disclaimer on the "authorize" about the fact that all is local, no external server involved on the Auth would be great I think. (because it is a great achievment)

Love the idea, keep up the great work

**Comment by Kuranes** [comment]
not sure about the auth, hacked in dev tools the css selector and tried to get access, but it spawned an auth page whereas my repo isn't private. strange ?
(and it didn't work even after auth )

**Comment by patmood** [comment]
Hi @Kuranes, I haven't work on this for a while - What issue are you having?

**Comment by Kuranes** [comment]
Hi, it's those selectors that doesn't work here:

https://github.com/patmood/git-time-machine/blob/891f1ce09d4bc949054ff40f70a58080f71f51bb/browser_extensions/chrome/time_machine_button.js#L15

**Comment by patmood** [comment]
@Kuranes thanks for pointing that out!

I've updated it and pushed it out to the chrome store. Look for v1.2

**Comment by Kuranes** [comment]
Working, Thanks a lot !
